# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20170722_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
    ]
